Fix passing incompatible pointer type with GCC 14
GCC 14 (and newer compilers like Clang 16) enables
-Wincompatible-pointer-types by default, along with some other flags.
Thus resulting in build errors such as

util-host-info.c: In function ‘SCKernelVersionIsAtLeast’:
util-host-info.c:94:31: error: passing argument 1 of ‘pcre2_substring_list_free_8’ from incompatible pointer type [-Wincompatible-pointer-types]
   94 |     pcre2_substring_list_free((PCRE2_SPTR *)list);
      |                               ^~~~~~~~~~~~~~~~~~
      |                               |
      |                               const PCRE2_UCHAR8 ** {aka const unsigned char **}

Removing the casting make suricata build with GCC 14.

First discovered on Gentoo Linux with GCC 14

Bug: https://bugs.gentoo.org/925011
Signed-off-by: Brahmajit Das <brahmajit.xyz@gmail.com>